# Generated by Django 2.2.2 on 2021-03-18 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=254)),
                ('city', models.CharField(default='', max_length=500)),
                ('product', models.CharField(default='', max_length=500)),
                ('quantity', models.CharField(default='', max_length=500)),
                ('your_message', models.CharField(default='', max_length=500)),
                ('contact_created_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
