# Generated by Django 2.2.2 on 2021-03-19 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Tittle', models.CharField(max_length=500)),
                ('productdescription', models.TextField(max_length=5000)),
                ('price', models.CharField(max_length=50)),
                ('usage_description', models.TextField(max_length=5000)),
                ('product_created', models.DateTimeField(default=datetime.datetime.now)),
                ('display_image_1', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('display_image_2', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
            ],
        ),
    ]
