# Generated by Django 2.2.2 on 2021-04-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_tittle', models.CharField(max_length=500)),
                ('first_part_description', models.TextField(max_length=5000)),
                ('second_part_description', models.TextField(max_length=5000)),
                ('main_image', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('second_section_tittle', models.CharField(max_length=500)),
                ('second_part_description1', models.TextField(max_length=5000)),
                ('second_part_description2', models.TextField(max_length=5000)),
                ('second_part_image', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('third_section_tittle', models.CharField(max_length=500)),
                ('third_part_description', models.TextField(max_length=5000)),
                ('third_part_point1', models.TextField(max_length=5000)),
                ('third_part_point2', models.TextField(max_length=5000)),
                ('third_part_point3', models.TextField(max_length=5000)),
                ('third_part_point4', models.TextField(max_length=5000)),
                ('third_part_point5', models.TextField(max_length=5000)),
                ('third_part_point6', models.TextField(max_length=5000)),
                ('third_part_image', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('forth_section_tittle', models.CharField(max_length=500)),
                ('forth_part_description1', models.TextField(max_length=5000)),
                ('forth_part_description2', models.TextField(max_length=5000)),
                ('forth_part_description3', models.TextField(max_length=5000)),
                ('forth_part_description4', models.TextField(max_length=5000)),
                ('forth_part_description5', models.TextField(max_length=5000)),
            ],
        ),
    ]
