# Generated by Django 2.2.2 on 2021-04-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='list_tittle',
            field=models.CharField(default='list - tittle', max_length=500),
        ),
    ]
