# Generated by Django 2.2.2 on 2021-04-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_resources_list_tittle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='forth_part_description1',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='forth_part_description2',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='forth_part_description3',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='forth_part_description4',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='forth_part_description5',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='forth_section_tittle',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='third_part_point5',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='third_part_point6',
        ),
        migrations.AddField(
            model_name='resources',
            name='Frequently_Asked_Questions',
            field=models.CharField(default='Question', max_length=500),
        ),
        migrations.AddField(
            model_name='resources',
            name='question_description_1',
            field=models.TextField(default='description', max_length=5000),
        ),
        migrations.AddField(
            model_name='resources',
            name='question_description_2',
            field=models.TextField(default='description', max_length=5000),
        ),
        migrations.AddField(
            model_name='resources',
            name='question_description_3',
            field=models.TextField(default='description', max_length=5000),
        ),
        migrations.AddField(
            model_name='resources',
            name='question_description_4',
            field=models.TextField(default='description', max_length=5000),
        ),
        migrations.AddField(
            model_name='resources',
            name='question_description_5',
            field=models.TextField(default='description', max_length=5000),
        ),
        migrations.AddField(
            model_name='resources',
            name='question_tittle_1',
            field=models.CharField(default='tittle', max_length=5000),
        ),
        migrations.AddField(
            model_name='resources',
            name='question_tittle_2',
            field=models.CharField(default='tittle', max_length=5000),
        ),
        migrations.AddField(
            model_name='resources',
            name='question_tittle_3',
            field=models.CharField(default='tittle', max_length=5000),
        ),
        migrations.AddField(
            model_name='resources',
            name='question_tittle_4',
            field=models.CharField(default='tittle', max_length=5000),
        ),
        migrations.AddField(
            model_name='resources',
            name='question_tittle_5',
            field=models.CharField(default='tittle', max_length=5000),
        ),
    ]
