# Generated by Django 2.2.2 on 2021-04-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210406_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='home_main_title',
            field=models.CharField(default='home -main - tittle', max_length=500),
        ),
    ]
