# Generated by Django 2.2.2 on 2021-04-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_resources_home_main_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchLocator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(default='list - tittle', max_length=500)),
                ('branch_adress', models.CharField(default='home -main - tittle', max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=500)),
                ('latitude', models.CharField(max_length=500)),
                ('main_image_1', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('main_image_2', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('main_image_3', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('main_image_4', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('main_image_5', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('main_image_6', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('main_image_7', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
            ],
        ),
    ]
