# Generated by Django 2.2.2 on 2021-04-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_branchlocator'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchlocator',
            name='phone_number',
            field=models.CharField(default='-------', max_length=500),
        ),
        migrations.AlterField(
            model_name='branchlocator',
            name='city',
            field=models.CharField(default='-------', max_length=500),
        ),
    ]
