# Generated by Django 2.2.2 on 2022-09-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210407_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
